version: '3.8'

services:
  rplay-live-dl:
    image: rplay-live-dl:latest
    container_name: rplay-live-dl
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    volumes:
      - ./env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./archive:/app/archive
      - ./logs:/app/logs
    restart: unless-stopped