"""Shared constants used across modules."""

RPLAY_SITE_URL = "https://rplay.live"
RPLAY_PROFILE_PHOTO_BASE_URL = "https://pb3.rplay.live/profilePhoto"
DEFAULT_RPLAY_API_BASE_URL = "https://api.rplay.live"

DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
)

DEFAULT_HTTP_HEADERS = {
    "User-Agent": DEFAULT_USER_AGENT,
    "Referer": RPLAY_SITE_URL,
    "Origin": RPLAY_SITE_URL,
}

DEFAULT_REQUEST_TIMEOUT = 30  # seconds
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_BACKOFF_FACTOR = 0.5
RETRY_STATUS_CODES = [429, 500, 502, 503, 504]
DEFAULT_TOKEN_REFRESH_LEEWAY_SECONDS = 300

DEFAULT_DOWNLOAD_RETRIES = 10
DEFAULT_FRAGMENT_RETRIES = 10
DEFAULT_DOWNLOAD_SOCKET_TIMEOUT = 10
DEFAULT_DOWNLOAD_TASK_RETRY_BACKOFF_FACTOR = 2.0

DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_MAX_SIZE_MB = 5
DEFAULT_LOG_BACKUP_COUNT = 5
DEFAULT_LOG_RETENTION_DAYS = 30
DEFAULT_LOG_YTDLP_INTERNAL = False

# Minimum free disk space (GiB) before starting a recording; 0 disables
DEFAULT_MIN_FREE_DISK_GB = 5.0

# Archive capacity alerts (GiB); alerts never stop an active recording
DEFAULT_DISK_WARNING_GB = 30.0
DEFAULT_DISK_CRITICAL_GB = 10.0
DEFAULT_DISK_RECOVERY_MARGIN_GB = 2.0
DEFAULT_DISK_REMINDER_SECONDS = 3600

# Merge preflight: free space must cover input bytes x multiplier + reserve GiB.
# 1.1 budgets the FFmpeg temp output; a failed copy fallback keeps raw inputs.
DEFAULT_MERGE_MIN_FREE_DISK_GB = 1.0
DEFAULT_MERGE_SPACE_MULTIPLIER = 1.1

# Ceiling for one ffmpeg concat merge, shared by the live executor and orphan recovery
DEFAULT_MERGE_TIMEOUT_SECONDS = 7200

# Poll interval default (INTERVAL env); shared by EnvConfig and the health probe
DEFAULT_INTERVAL = 60

__all__ = [
    "RPLAY_SITE_URL",
    "RPLAY_PROFILE_PHOTO_BASE_URL",
    "DEFAULT_RPLAY_API_BASE_URL",
    "DEFAULT_USER_AGENT",
    "DEFAULT_HTTP_HEADERS",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_BACKOFF_FACTOR",
    "RETRY_STATUS_CODES",
    "DEFAULT_TOKEN_REFRESH_LEEWAY_SECONDS",
    "DEFAULT_DOWNLOAD_RETRIES",
    "DEFAULT_FRAGMENT_RETRIES",
    "DEFAULT_DOWNLOAD_SOCKET_TIMEOUT",
    "DEFAULT_DOWNLOAD_TASK_RETRY_BACKOFF_FACTOR",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_MAX_SIZE_MB",
    "DEFAULT_LOG_BACKUP_COUNT",
    "DEFAULT_LOG_RETENTION_DAYS",
    "DEFAULT_LOG_YTDLP_INTERNAL",
    "DEFAULT_MIN_FREE_DISK_GB",
    "DEFAULT_DISK_WARNING_GB",
    "DEFAULT_DISK_CRITICAL_GB",
    "DEFAULT_DISK_RECOVERY_MARGIN_GB",
    "DEFAULT_DISK_REMINDER_SECONDS",
    "DEFAULT_MERGE_MIN_FREE_DISK_GB",
    "DEFAULT_MERGE_SPACE_MULTIPLIER",
    "DEFAULT_MERGE_TIMEOUT_SECONDS",
    "DEFAULT_INTERVAL",
]
