name: Docker Build and Push

on:
    push:
        tags:
            - "*"

jobs:
    docker-build-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get branch name
              id: branch
              run: |
                  if [[ $GITHUB_REF_NAME == ${{ github.event.ref }} ]]; then
                    echo "BRANCH_NAME=$(git branch -r --contains ${{ github.ref }} | grep -v HEAD | tail -1 | sed 's/.*origin\///')" >> $GITHUB_OUTPUT
                  else
                    echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
                  fi

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get tag name
              id: get_tag
              run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Set Docker tags
              id: docker_tags
              run: |
                  if [ "${{ steps.branch.outputs.BRANCH_NAME }}" = "main" ]; then
                    echo "TAGS=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_tag.outputs.TAG_NAME }}" >> $GITHUB_OUTPUT
                  else
                    echo "TAGS=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_tag.outputs.TAG_NAME }}" >> $GITHUB_OUTPUT
                  fi

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.docker_tags.outputs.TAGS }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
